## 1.4.1. 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [1]:
import pandas as pd

In [2]:
titanic_df = pd.read_csv(r'.\kaggle\titanic\titanic_train.csv')
titanic_df.head(3) #데이터의 상위 N개 출력. 기본은 5개

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [6]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
value_counts = titanic_df['Pclass'].value_counts()
# [] 사용 시 해당 칼럼 데이터 세트가 series 형태로 반환
# value_counts()는 해당 칼럼값의 유형과 건수 확인. 데이터 분포도 확인에 유용
print(value_counts)
print(type(value_counts)) #Series 객체 반환. DataFrame 자체는 value_counts 메서드 없음

3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>

In [10]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass)) # Series는 Index와 1개의 칼럼으로만 구성된 데이터 세트
titanic_pclass.head() #왼쪽은 Dataframe의 인덱스. 오른쪽은 칼럼의 데이터값

<class 'pandas.core.series.Series'>

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

## 1.4.2. DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호변환

In [3]:
import numpy as np

### 1차원 데이터를 DataFrame로 변환 : column이 1개만 필요
col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1) #리스트를 ndarray로 변환
print('array1 shape : ', array1.shape)

# 리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

# ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape :  (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [5]:
### 2차원 데이터를 DataFrame로 변환
col_name2 = ['col1', 'col2', 'col3']
list2 = [[1, 2, 3], [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape : ', array2.shape)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)

df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape :  (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [6]:
### 딕셔너리를 DataFrame로 변환 : 딕셔너리의 key를 칼럼명(문자열)으로, value를 칼럼 데이터(리스트, ndarray)로 변환
dict = {'col1':[1, 11], 'col2':[2, 12], 'col3':[3, 13]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [7]:
### DataFrame을 ndarray로 변환 : values 이용
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shpae:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shpae: (2, 3)
[[ 1  2  3]
 [11 12 13]]

In [8]:
### DataFrame을 리스트로 변환 : tolist() 이용
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 12, 13]]

In [11]:
### DataFrame을 딕셔너리로 변환 : to_dict() 이용, 'list'를 인자로 전달해 리스트형으로 반환
dict3 = df_dict.to_dict('list')
print('df_dict.values.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}

## DataFrme의 칼럼 데이터 세트 생성과 수정
**[] 연산자 이용해 구현 가능**

In [14]:
### 새 column을 추가하고 일괄적 상수 할당
titanic_df['Age_0'] = 0 #새로운 칼럼 Age_0을 추가하고 일괄적으로 0을 할당(Series)
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [15]:
### 새 column을 추가하고 기존 칼럼 Series 데이터를 이용해 값 할당
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [16]:
### 기존 column을 일괄적으로 업데이트
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

## DataFrame 데이터 삭제
**drop(labels, axis, index, columns, level, inplace, errors) 메서드 이용**
1. axis=0은 행을, axis=1은 열을 가리킴. 행 삭제 시 label은 인덱스 값이며, 열 삭제 시 label은 column명
2. inplace는 기본이 False이며 원본은 그대로 두고 반환, True로 설정 시 원본 데이터까지 삭제 후 None을 반환

In [17]:
### column의 삭제
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [18]:
### 여러 column의 삭제
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True) #inplace=True면 None 반환하므로 할당하면 안됨
print('inplace=True로 drop 후 반환된 값 : ', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값 :  None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [20]:
### row의 삭제
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)

print('---before axis 0 drop---')
print(titanic_df.head(3))

titanic_df.drop([0, 1, 2], axis=0, inplace=True)
print('---after axis 0 drop---')
print(titanic_df.head(3))

---before axis 0 drop---
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
---after axis 0 drop---
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

## Index 객체
* Pandas의 Index 객체 : 
  * DataFrame, Series의 데이터를 고유하게 식별하는 객체
  * 식별성 데이터를 1차원 array로 가짐
  * 한 번 만들어진 DataFrame 및 Series의 Index 객체를 변경 못함
  * Series 객체는 Index 객체를 포함하나, Series 객체에 연산 함수 적용 시 Index는 제외됨 -> 오로지 식별 용
* DataFrame.index 혹은 Series.index 속성 : 객체 추출
* Index.values 속성 : 객체 값 리턴

In [6]:
titanic_df = pd.read_csv(r'./kaggle/titanic/titanic_train.csv') #drop으로 삭제된 데이터 있어서, 새 데이터 불러오기

indexes = titanic_df.index #index 객체 추출
print(indexes)
print('Index 객체 array값:\n', indexes.values) #index 객체의 ndarray값

NameError: name 'pd' is not defined

In [23]:
print(type(indexes.values)) #index 객체의 타입
print(indexes.values.shape) #index 객체의 형상
print(indexes[:5].values) #상위 5개의 값 추출
print(indexes.values[:5]) #상위 5개의 값 추출(위와 동일)
print(indexes[6]) #특정 위치의 값 추출

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [24]:
indexes[0] = 5

TypeError: Index does not support mutable operations

In [11]:
series_fair = titanic_df['Fare']
print('Fair Series max 값 : ', series_fair.max())
print('Fair Series min 값 : ', series_fair.min())
print('sum() Fair Series : ', sum(series_fair))
print('Fair Series + 3 :\n', (series_fair + 3).head(3))

Fair Series max 값 :  512.3292
Fair Series min 값 :  0.0
sum() Fair Series :  28693.949299999967
Fair Series + 3 :
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

In [12]:
titanic_reset_df = titanic_df.reset_index(inplace=False) 
#reset_index() 메서드 : 
# 새롭게 인덱스를 연속 숫자형으로 할당. 기존 인덱스는 index라는 새 칼럼명으로 추가됨
# 인덱스가 연속된 int형 데이터가 아닐 경우 이를 다시 int형 숫자 데이터로 바꿀 때 주로 사용
# series에 메서드 적용 시 DataFrame이 됨에 주의

titanic_reset_df.head(3)

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [13]:
print('--- before reset_index ---')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('values_counts 객체 변수 타입 : ', type(value_counts))

print('--- after reset_index ---')
new_value_counts = value_counts.reset_index(inplace=False)
print(new_value_counts)
print('new_value_counts 객체 변수 타입 : ', type(new_value_counts))

--- before reset_index ---
3    491
1    216
2    184
Name: Pclass, dtype: int64
values_counts 객체 변수 타입 :  <class 'pandas.core.series.Series'>
--- after reset_index ---
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입 :  <class 'pandas.core.frame.DataFrame'>

## 데이터 셀렉션 및 필터링
* 넘파이의 []연산자와 유사한 부분도 있고 다른 부분도 있음에 주의
  * 칼럼명 문자 또는 인덱스로 변환 가능한 표현식만 안에 들어갈 수 있음
  * boolean 인덱싱 표현도 가능. 원하는 데이터를 편리하게 추출해 자주 사용함
  * 슬라이싱 연산은 비추천
* ix[] 연산자
  * 열, 행 순으로 입력해 특정 위치값을 리턴
  * 열은 칼럼 번호 또는 칼럼 이름으로
  * 행은 인덱스 번호로
  * 혼돈이 많아 사라짐 -> 칼럼 명칭 기반 인덱싱 연산자 loc[], 칼럼 위치 기반 인덱싱 연산자 iloc[] 만들어짐
 * 명칭(Label) 기반 인덱싱과 위치(Position) 기반 인덱싱
   * 명칭 기반 인덱싱 : 칼럼의 명칭을 기반으로 위치를 지정하는 방식
   * 위치 기반 인덱싱 : 0을 출발점으로 하는 가로/세로축 좌표 기반의 행과 열 위치를 기반으로 데이터 지정
   * DataFrame의 인덱싱은 명칭 기반 인덱싱 -> 행 위치의 인덱스값과 위치기반 인덱싱이 integer형일 때 코드 작성에 혼돈 초래 가능
   * 칼럼 명칭 기반 인덱싱 연산자 loc[], 칼럼 위치 기반 인덱싱 연산자 iloc[] 사용
 * 불린 인덱싱
   * 명확히 인덱싱을 지정한느 방식보다 불린 인덱싱으로 데이터를 가져오는 경우가 많음. ix[] 등 내에 입력 시 원하는 값 필터링

In [14]:
### DataFrame의 []연산자
print('단일 칼럼 데이터 추출 : \n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출 : \n', titanic_df[['Survived', 'Pclass']].head(3))
print('[ ] 안에 숫자 index는 keyerror 오류 발생 : \n', titanic_df[0])

단일 칼럼 데이터 추출 :
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출 :
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

In [15]:
titanic_df[0:2] #슬라이싱 사용

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [16]:
titanic_df[titanic_df['Pclass']==3].head(3) #불린 인덱싱 사용

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S

In [6]:
### DataFrame의 ix[] 연산자 : 위치&명칭 기반 인덱싱 모두를 허용
data = {'Name':['Chulmin', 'Eunkyeong', 'Jinwoong', 'Soobeom'],
       'Year' : [2011, 2016, 2015, 2016],
       'Gender':['Male', 'Female', 'Male', 'Male']}
data_df = pd.DataFrame(data, index=['One', 'Two', 'Three', 'Four'])
data_df #인덱스로 문자열 할당

data_df_reset = data_df.reset_index() #reset_index()로 새로운 숫자형 인덱스 생성
data_df_reset = data_df_reset.rename(columns={'index':'old_index'})

data_df_reset.index = data_df_reset.index + 1 #인덱스값에 1을 더해 1부터 시작하는 새로운 인덱스값 생성
data_df_reset

  old_index       Name  Year  Gender
1       One    Chulmin  2011    Male
2       Two  Eunkyeong  2016  Female
3     Three   Jinwoong  2015    Male
4      Four    Soobeom  2016    Male

In [7]:
### DataFrame의 iloc[] 연산자 : 위치 기반 인덱싱만 허용하여, 행과 열 값으로 integer/integer형의 슬라이싱, 팬시 리스트 값. boolean 인덱싱 제공 안함
data_df.iloc[0 ,0]

'Chulmin'

In [10]:
### DataFrame의 loc[] 연산자 : 명칭 기반 인덱싱. 행에는 DataFrame의 index값을, 열 위치는 칼럼명을 입력
data_df.loc['One', 'Name']

'Chulmin'

In [13]:
### 명칭 기반/위치 기반 인덱싱에서의 슬라이싱 차이 : 명칭 기반 인덱싱은 마지막 위치 -1 범위가 아니라, 마지막 위치까지를 가리킴
# print('명칭 기반 ix 슬라이싱 : \n', data_df.ix['one':'two', 'Name'], '\n')
print('위치 기반 iloc 슬라이싱 : \n', data_df.iloc[0:1, 0], '\n')
print('명칭 기반 loc 슬라이싱 : \n', data_df.loc['One':'Two', 'Name'])

위치 기반 iloc 슬라이싱 :
 One    Chulmin
Name: Name, dtype: object

명칭 기반 loc 슬라이싱 :
 One      Chulmin
Two    Eunkyeong
Name: Name, dtype: object

In [14]:
### 불린 인덱싱
titanic_df = pd.read_csv(r'./kaggle/titanic/titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age']>60] #Age가 60 이상인 데이터만 추출
[print(type(titanic_boolean))]
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [15]:
titanic_df[titanic_df['Age']>60][['Name', 'Age']].head(3) #Age가 60 이상인 데이터 중 Name, Age만 추출
titanic_df.loc[titanic_df['Age']>60, ['Name', 'Age']].head(3) #loc 사용. 위와 같은 결과

                              Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [17]:
titanic_df[(titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')] #복합조건 적용

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [20]:
condition1 = titanic_df['Age'] > 60
condition2 = titanic_df['Pclass'] == 1
condition3 = titanic_df['Sex']=='female'
titanic_df[condition1 & condition2 & condition3]  #개별 조건을 할당하고 변수 결합해 불린 인덱싱 적용

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

## 정렬, Aggregation 함수, GroupBy 적용

In [21]:
### DataFrmae, Series 의 정렬 : sort_values()
titanic_sorted = titanic_df.sort_values(by=['Name']) #파라미터 by를 이용해 특정 칼럼으로 정렬
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,NaN,S

In [22]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False) #여러 개의 칼럼으로 정렬, 파라미터 ascending 이용해 내림차순
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,NaN,S
282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5,NaN,S

In [23]:
### Aggregation 함수 적용 : min(), max(), sum(), count()
titanic_df.count() #모든 칼럼에 해당 aggregation 적용함

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [24]:
titanic_df[['Age', 'Fare']].mean() #특정 칼럼에 적용

Age     29.699118
Fare    32.204208
dtype: float64

In [28]:
### GroupBy() 적용 : 입력 파라미터에 by 칼럼 입력 시 대상 칼럼으로 groupby됨 & DataFrameGroupBy라는 또다른 형태의 DataFrame 반환
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

titanic_groupby = titanic_df.groupby(by='Pclass').count() #groupby 의 반환 결과에 aggregation 함수 적용 시 groupby 대상 칼럼 제외한 모든 칼럼에 agrregation 적용
titanic_groupby

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491

In [30]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby
#groupby에 특정 칼럼만 aggregation 함수 적용하려면 DataFrameGroupBy 객체에 해당 칼럼 필터링 뒤 aggregation 함수 적용

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [31]:
titanic_df.groupby('Pclass')['Age'].agg([max, min]) # 적용하려는 여러 개의 aggregation 함수 명을 DataFrameGruopBy 객체에 agg()내에 인자로 입력해 사용

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [32]:
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'} #agg() 내에 입력값으로 딕셔너리로 aggregation이 적용될 칼럼과 함수 입력
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

## 결손 데이터(Missing Data) 처리
* 결손 데이터 : 칼럼에 값이 없는 Null인 경우 -> 넘파이의 NaN으로 표시
* 결손 데이터 처리 이유 
  * 머신러닝 알고리즘은 NaN 값을 처리하지 않으므로 다른 값으로 대체
  * 함수 연산(max, mean 등)에서 제외됨
 * isna()로 NaN 여부 확인, fillna()로 Nan 값을 다른 값으로 대체

In [33]:
### isna()로 결손 데이터 여부 확인 -> T/F로 알려줌
titanic_df.isna().head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False

In [36]:
titanic_df.isna().sum() #결손대에터 개수를 sum()으로 구현 -> True는 숫자1, False는 0

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [38]:
### fillna()로 결손 데이터 대체하기 : 실제 데이터 세트값을 변경시키려면 inplace=True로 설정하거나 반환값을 다시 받아야 함
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C000,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C000,S

In [39]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean()) #Age 칼럼의 Nan 값을 평균나이로
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S') #Embarked칼럼의 Nan값을 S로 대체
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## apply lambda 식으로 데이터 가공
* apply 함수에 lambda 식을 결합해 DataFrame/Series의 레코드 별로 데이터를 가공하는 기능 제공
* 칼럼에 일괄적으로 데이터 가공하는 것이 속도 면에서 빠르거나/복잡한 데이터 가공 필요할 시 apply lambda 이용

In [40]:
### lambda 함수 : lambda 식 이용 시 여러 개의 값을 입력 인자로 사용해야 할 때는 map() 함수 결합
a=[1, 2, 3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [41]:
### 판다스 DataFrame의 lambda 식
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x: len(x)) #Name 칼럼의 문자열 개수를 별도 칼럼으로 생성
titanic_df[['Name', 'Name_len']].head(3)

                                                Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [43]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [44]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))
# lambda는 else if 지원하지 않으므로 중첩해 사용함
titanic_df['Age_cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64

In [45]:
def get_category(age):
    cat = ''
    if age<=5 : cat = 'Baby'
    elif age<=12 : cat = 'Child'
    elif age<=18 : cat = 'Teenager'
    elif age<=25 : cat = 'Student'
    elif age<=35 : cat = 'Young Adult'
    elif age<=60 : cat = 'Adult'
    else : cat = 'Elderly'
    return cat

titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_category(x)) #함수를 lambda 식 안에 적용 가능
titanic_df[['Age', 'Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult

## 기타
* 파이썬 대표적 시각화 패키지 : Matplotlib, Seaborn
* 시본은 https://seaborn.pydata.org/index.html 방문해 예제 수행해도 도움됨